// page.tsx

"use client";

import { useEffect, useState, useCallback } from "react";
import { sdk } from "@farcaster/miniapp-sdk";
import { useAccount } from "wagmi";
import { HeroSection } from "@/components/HeroSection";
import { BadgeSection } from "@/components/BadgeSection";
import { MintButton } from "@/components/MintButton";
import { MintPaidButton } from "@/components/MintPaidButton";
import { SuccessModal } from "@/components/SuccessModal";
import { TopSection } from "@/components/TopSection";
import { SplashScreen } from "@/components/SplashScreen";
import { BeforeMintShareBar } from "@/components/BeforeMintShareBar";
import { useWarplets } from "@/hooks/useWarplets";
import { useGenerationStorage } from "@/hooks/useGenerationStorage";
import { useSplashTransition } from "@/hooks/useSplashTransition";
import { checkFidMinted, sanitizeImageData } from "@/lib/generators";
import { GEOPLET_CONFIG } from "@/lib/contracts";
import { getNFTById, GEOPLET_ADDRESS } from "@/lib/rarible";
import { toast } from "sonner";

export default function Home() {
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isMinted, setIsMinted] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [mintTxHash, setMintTxHash] = useState<string | null>(null);
  const [mintedTokenId, setMintedTokenId] = useState<string | null>(null);
  const [serviceError, setServiceError] = useState<string | null>(null);
  const [isPageLoading, setIsPageLoading] = useState(true);
  const [paymentStatus, setPaymentStatus] = useState<
    "paid" | "unpaid" | "checking"
  >("checking");

  const { address } = useAccount();
  const { nft, fid, username, isLoading: isLoadingWarplet, hasWarplet } = useWarplets();
  const {
    saveGeneration,
    loadGeneration,
    isLoading: isLoadingStorage,
  } = useGenerationStorage();

  // Initialize Farcaster SDK with environment detection
  useEffect(() => {
    const initSdk = async () => {
      try {
        const inMiniApp = await sdk.isInMiniApp();

        if (!inMiniApp) {
          console.log("[SDK] Not in mini app environment");
          toast.info(
            "⚠️ This app is designed for Farcaster. Some features may be limited.",
            { duration: 5000 }
          );
        }

        await sdk.actions.ready();
      } catch (error) {
        console.error("[SDK] Initialization failed:", error);
      }
    };

    initSdk();
  }, []);

  // Load saved generation on mount (if exists)
  useEffect(() => {
    if (!fid || !address) return;

    const loadSavedGeneration = async () => {
      // Check if FID is already minted
      const fidIsMinted = await checkFidMinted(fid.toString());

      if (fidIsMinted) {
        // FID is minted - fetch from Rarible by tokenId (FID = tokenId)
        console.log("[LOAD-GEN] FID minted, fetching from Rarible...");
        setIsMinted(true);

        try {
          const nft = await getNFTById(GEOPLET_ADDRESS, fid.toString());

          if (nft.image) {
            setGeneratedImage(nft.image);
            setHasAutoGenerated(true);
            console.log("[LOAD-GEN] Loaded minted Geoplet from Rarible");
          } else {
            console.warn("[LOAD-GEN] Minted NFT found but no image available");
            setHasAutoGenerated(true); // Prevent auto-generation
          }
        } catch (error) {
          console.error("[LOAD-GEN] Failed to fetch from Rarible:", error);
          // If Rarible fails, still prevent auto-generation since FID is minted
          setHasAutoGenerated(true);
        }
      } else {
        // FID not minted - load from Supabase if available
        setIsMinted(false);
        const savedImage = await loadGeneration(fid);
        if (savedImage) {
          setGeneratedImage(savedImage);
          setHasAutoGenerated(true);
          console.log("[LOAD-GEN] Loaded saved generation from Supabase");
        }
      }
    };

    loadSavedGeneration();
  }, [fid, address, loadGeneration]);

  // Check payment status on mount (for payment tracker system)
  useEffect(() => {
    async function checkPaymentStatus() {
      if (!fid) {
        setPaymentStatus("unpaid");
        return;
      }

      try {
        console.log("[PAYMENT-CHECK] Checking payment status for FID:", fid);

        const response = await fetch(`/api/payment-tracking/${fid}`);
        const data = await response.json();

        if (data.success && data.data.status === "settled") {
          console.log("[PAYMENT-CHECK] ✅ Settled payment found:", {
            fid,
            settlement_tx_hash: data.data.settlement_tx_hash,
          });

          setPaymentStatus("paid");

          // Load image from Supabase if not already loaded
          if (!generatedImage) {
            const savedImage = await loadGeneration(fid);
            if (savedImage) {
              // Sanitize image to prevent double-prefix bug
              const sanitizedImage = sanitizeImageData(savedImage);
              setGeneratedImage(sanitizedImage);
              console.log(
                "[PAYMENT-CHECK] Loaded and sanitized image from Supabase"
              );
            }
          }
        } else {
          console.log("[PAYMENT-CHECK] No settled payment found:", { fid });
          setPaymentStatus("unpaid");
        }
      } catch (error) {
        console.error("[PAYMENT-CHECK] Error checking payment status:", error);
        setPaymentStatus("unpaid");
      }
    }

    checkPaymentStatus();
  }, [fid, loadGeneration, generatedImage]);

  // Control page loading state - hide splash when critical data is ready
  useEffect(() => {
    // Show splash until we have all critical data
    const hasWallet = !!address;
    const warpletCheckComplete = !isLoadingWarplet; // Warplet check finished (exists or 404)
    const storageCheckComplete = !isLoadingStorage;

    if (hasWallet && warpletCheckComplete && storageCheckComplete) {
      // Small delay for smooth transition
      const timer = setTimeout(() => {
        setIsPageLoading(false);
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [address, isLoadingWarplet, isLoadingStorage]);

  // Trigger GSAP transition when loading completes
  useSplashTransition(isPageLoading);

  // Auto-generate after wallet connection and Warplet data loads
  useEffect(() => {
    if (!address || !nft || !fid || hasAutoGenerated || isGenerating) return;

    const autoGenerate = async () => {
      setIsGenerating(true);
      try {
        // Check if FID is already minted
        console.log("[AUTO-GEN] Checking if FID is already minted...");
        const fidIsMinted = await checkFidMinted(fid.toString());

        if (fidIsMinted) {
          // FID already minted - fetch and display the minted Geoplet from Rarible
          console.log(
            "[AUTO-GEN] FID already minted, fetching minted Geoplet from Rarible..."
          );
          setIsMinted(true);

          try {
            const nft = await getNFTById(GEOPLET_ADDRESS, fid.toString());

            if (nft.image) {
              setGeneratedImage(nft.image);
              toast.success("Displaying your minted Geoplet!");
              console.log("[AUTO-GEN] Minted Geoplet displayed successfully");
            } else {
              console.warn(
                "[AUTO-GEN] Minted NFT found but no image available"
              );
              toast.error("Minted NFT found but no image available");
            }
          } catch (raribleError) {
            console.error(
              "[AUTO-GEN] Failed to fetch minted Geoplet from Rarible:",
              raribleError
            );
            toast.error("Failed to fetch minted Geoplet");
          }

          setHasAutoGenerated(true);
          setIsGenerating(false);
          return; // Exit early - don't generate
        }

        // FID not minted - continue with normal auto-generation
        console.log(
          "[AUTO-GEN] FID not minted, proceeding with auto-generation..."
        );
        setIsMinted(false);

        // Pre-check OpenAI availability
        console.log("[AUTO-GEN] Step 0: Checking OpenAI availability...");
        const precheckResponse = await fetch("/api/openai-precheck", {
          method: "GET",
          headers: { "Content-Type": "application/json" },
        });

        const precheckData = await precheckResponse.json();

        if (!precheckResponse.ok || !precheckData.available) {
          throw new Error(
            precheckData.reason || "OpenAI service temporarily unavailable"
          );
        }

        console.log("[AUTO-GEN] ✅ OpenAI service available");

        // Call generation API
        const response = await fetch("/api/generate-image", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            imageUrl: nft.thumbnailUrl || nft.imageUrl,
            tokenId: nft.tokenId,
            name: `Warplet #${nft.tokenId}`,
            fid: fid.toString(), // Add FID for free generation check
          }),
        });

        const data = await response.json();

        if (!data.success || !data.imageData) {
          throw new Error(data.error || "Generation failed");
        }

        // Save to Supabase
        console.log("[AUTO-GEN] Attempting to save to Supabase", {
          fid,
          username,
          imageSize: data.imageData.length,
          imageSizeKB: (data.imageData.length / 1024).toFixed(2),
        });

        const saved = await saveGeneration(fid, data.imageData, username || `fid-${fid}`);
        if (!saved) {
          console.error("[AUTO-GEN] ❌ FAILED TO SAVE:", {
            fid,
            imageDataLength: data.imageData.length,
          });
          toast.error(
            `Failed to save image for FID ${fid}. Image may be too large. Check console for details.`,
            {
              duration: 5000,
            }
          );
          // Note: Image still displays in memory, but won't persist after app closure
        } else {
          console.log("[AUTO-GEN] ✅ Saved to Supabase successfully");
        }

        // Update state
        setGeneratedImage(data.imageData);
        setHasAutoGenerated(true);
        console.log("[AUTO-GEN] Auto-generation completed successfully");
      } catch (error) {
        console.error("Auto-generation failed:", error);

        const errorMessage =
          error instanceof Error ? error.message : "Unknown error";

        // Set friendly error message based on failure reason
        let friendlyError =
          "😅 Auto-gen unavailable. Try Regenerate or refresh!";

        if (
          errorMessage.toLowerCase().includes("openai") ||
          errorMessage.toLowerCase().includes("service")
        ) {
          if (errorMessage.toLowerCase().includes("credit")) {
            friendlyError = "🔧 Our Agent is refueling!";
          } else if (errorMessage.toLowerCase().includes("rate")) {
            friendlyError =
              "⚡ Engine warming up. Try Regenerate or wait a moment!";
          } else {
            friendlyError = "🎨 Our artist is taking a break.!";
          }
        }

        setServiceError(friendlyError);
        setHasAutoGenerated(true); // Prevent auto-retry loop
        toast.error(friendlyError, { duration: 8000 });
      } finally {
        setIsGenerating(false);
      }
    };

    // Small delay to show Warplet first
    const timer = setTimeout(() => {
      autoGenerate();
    }, 5000);

    return () => clearTimeout(timer);
  }, [address, nft, fid, hasAutoGenerated, isGenerating, saveGeneration]);

  return (
    <>
      {/*   h Screen */}
      {isPageLoading && <SplashScreen />}

      {/* Main Content */}
      <div id="main-content" style={{ opacity: isPageLoading ? 0 : 1 }}>
        {/* Top Section */}
        <TopSection />

        {/* Main Content */}
        <main className="flex-1 flex flex-col gap-8 px-4 pb-20">
          {/* Warplet Not Found - Show Error Immediately */}
          {!isLoadingWarplet && !hasWarplet && fid && (
            <div className="max-w-2xl mx-auto px-4 py-12 text-center mt-4">
              <h2 className="text-2xl font-semibold mb-3 text-gray-800">
                Warplet #{fid} Not Found
              </h2>
              <p className="text-sm text-gray-500">
                You need Warplet #{fid} that tied to your FID to create your
                Geoplet.
              </p>
            </div>
          )}

          {/* Normal App - Show when Warplet exists */}
          {hasWarplet && (
            <>
              {/* Hero Section */}
              <div className="mt-4">
                <HeroSection
                  warpletImage={nft?.thumbnailUrl || nft?.imageUrl || null}
                  warpletTokenId={nft?.tokenId || null}
                  generatedImage={generatedImage}
                  isGenerating={isGenerating}
                  isMinted={isMinted}
                />
              </div>

              {/* Badge Section - Trust signals and features */}
              <BadgeSection />

              {/* Mint Button - Conditional rendering based on payment status */}
              <div className="flex flex-col gap-4 justify-center items-center">
                {paymentStatus === "checking" ? (
                  <div className="text-center text-gray-400 py-4">
                    Checking payment status...
                  </div>
                ) : paymentStatus === "paid" ? (
                  <MintPaidButton
                    generatedImage={generatedImage}
                    onSuccess={(hash, tokenId) => {
                      setMintTxHash(hash);
                      setMintedTokenId(tokenId);
                      setShowSuccessModal(true);
                      setPaymentStatus("unpaid"); // Reset after successful mint
                    }}
                  />
                ) : (
                  <MintButton
                    generatedImage={generatedImage}
                    onSuccess={(hash, tokenId) => {
                      setMintTxHash(hash);
                      setMintedTokenId(tokenId);
                      setShowSuccessModal(true);
                    }}
                  />
                )}

                {/* Share Buttons - Below Mint Button */}
                <div className="w-full flex justify-center">
                  <BeforeMintShareBar fid={fid} variant="inline" />
                </div>
              </div>
            </>
          )}
        </main>

        {/* Success Modal */}
        <SuccessModal
          isOpen={showSuccessModal}
          onClose={() => {
            setShowSuccessModal(false);
            setGeneratedImage(null);
          }}
          image={generatedImage}
          txHash={mintTxHash}
          tokenId={mintedTokenId}
          fid={fid}
        />
      </div>
    </>
  );
}
