"use client";

import { useEffect, useState, useCallback } from "react";
import { sdk } from "@farcaster/miniapp-sdk";
import { useAccount } from "wagmi";
import { HeroSection } from "@/components/HeroSection";
import { RegenerateButton } from "@/components/RegenerateButton";
import { MintButton } from "@/components/MintButton";
import { SuccessModal } from "@/components/SuccessModal";
import { TopSection } from "@/components/TopSection";
import { WalletModal } from "@/components/WalletModal";
import { useWarplets } from "@/hooks/useWarplets";
import { useGenerationStorage } from "@/hooks/useGenerationStorage";
import { shareToFarcaster } from "@/lib/generators";
import { toast } from "sonner";

export default function Home() {
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [showWalletModal, setShowWalletModal] = useState(false);
  const [mintTxHash, setMintTxHash] = useState<string | null>(null);
  const [mintedTokenId, setMintedTokenId] = useState<string | null>(null);

  const { address } = useAccount();
  const { nft, fid } = useWarplets();
  const { saveGeneration, loadGeneration, deleteGeneration, isLoading: isLoadingStorage } =
    useGenerationStorage();

  // Initialize Farcaster SDK
  useEffect(() => {
    sdk.actions.ready().catch(console.error);
  }, []);

  // Load saved generation on mount (if exists)
  useEffect(() => {
    if (!fid || !address) return;

    const loadSavedGeneration = async () => {
      const savedImage = await loadGeneration(fid);
      if (savedImage) {
        setGeneratedImage(savedImage);
        setHasAutoGenerated(true);
      }
    };

    loadSavedGeneration();
  }, [fid, address, loadGeneration]);

  // Auto-generate after wallet connection and Warplet data loads
  useEffect(() => {
    if (!address || !nft || !fid || hasAutoGenerated || isGenerating) return;

    const autoGenerate = async () => {
      setIsGenerating(true);
      try {
        // Call generation API
        const response = await fetch("/api/generate-image", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            imageUrl: nft.thumbnailUrl || nft.imageUrl,
            tokenId: nft.tokenId,
            name: `Warplet #${nft.tokenId}`,
          }),
        });

        const data = await response.json();

        if (!data.success || !data.imageData) {
          throw new Error(data.error || "Generation failed");
        }

        // Save to Supabase
        const saved = await saveGeneration(fid, data.imageData);
        if (!saved) {
          console.warn("Failed to save generation to Supabase");
        }

        // Update state
        setGeneratedImage(data.imageData);
        setHasAutoGenerated(true);
      } catch (error) {
        console.error("Auto-generation failed:", error);
        toast.error("Failed to generate Geoplet");
      } finally {
        setIsGenerating(false);
      }
    };

    // Small delay to show Warplet first
    const timer = setTimeout(() => {
      autoGenerate();
    }, 1000);

    return () => clearTimeout(timer);
  }, [address, nft, fid, hasAutoGenerated, isGenerating, saveGeneration]);

  // Share handlers
  const handleFarcasterShare = async () => {
    if (!generatedImage || !nft) return;
    try {
      await shareToFarcaster(generatedImage, nft.tokenId, nft.name);
    } catch (error) {
      console.error("Failed to share:", error);
      toast.error("Failed to share to Farcaster");
    }
  };

  const handleXShare = () => {
    const text = "Check out my Geoplet! 🎨";
    const url = `https://geoplet.geoart.studio`;
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
    window.open(twitterUrl, "_blank");
  };

  return (
    <>
      {/* Top Section */}
      <TopSection
        onWalletClick={() => setShowWalletModal(true)}
        onFarcasterShare={generatedImage ? handleFarcasterShare : undefined}
        onXShare={generatedImage ? handleXShare : undefined}
      />

      {/* Main Content */}
      <main className="flex-1 flex flex-col gap-8 px-4 pb-20">
        {/* Hero Section */}
        <div className="my-4">
          <HeroSection
            warpletImage={nft?.thumbnailUrl || nft?.imageUrl || null}
            warpletTokenId={nft?.tokenId || null}
            generatedImage={generatedImage}
            isGenerating={isGenerating}
          />
        </div>

        {/* Split Buttons: Regenerate & Mint */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center my-4">
          <RegenerateButton
            disabled={!hasAutoGenerated}
            onRegenerate={(imageData) => {
              setGeneratedImage(imageData);
            }}
            onSaveToSupabase={async (imageData) => {
              if (!fid) return false;
              return await saveGeneration(fid, imageData);
            }}
          />
          <MintButton
            disabled={!generatedImage}
            generatedImage={generatedImage}
            onSuccess={(hash, tokenId) => {
              setMintTxHash(hash);
              setMintedTokenId(tokenId);
              setShowSuccessModal(true);
            }}
            onDeleteFromSupabase={async () => {
              if (!fid) return false;
              return await deleteGeneration(fid);
            }}
          />
        </div>
      </main>

      {/* Wallet Modal */}
      <WalletModal
        isOpen={showWalletModal}
        onClose={() => setShowWalletModal(false)}
      />

      {/* Success Modal */}
      <SuccessModal
        isOpen={showSuccessModal}
        onClose={() => {
          setShowSuccessModal(false);
          setGeneratedImage(null);
        }}
        image={generatedImage}
        txHash={mintTxHash}
        tokenId={mintedTokenId}
      />
    </>
  );
}
